// SPDX-License-Identifier: MIT-0

//! Golden normal-week grids for every shipped identity.
//!
//! The suite is strong on self-consistency and was weak on accuracy: a close
//! encoded fifteen minutes wrong, a `MON_FRI`/`MON_THU` day-mask flip, or a key
//! wired to a neighbour's profile all passed everything, because nothing
//! rendered the shipped tables in a form a human could diff against a source
//! document.
//!
//! This file is that rendering. It is not a correctness proof - a golden file
//! agrees with whatever is committed - but it converts every silent table edit
//! into a reviewable diff, and it covers all 94 exchanges and all 25 keys at
//! once rather than depending on someone remembering to hand-write a baseline.
//!
//! To regenerate after an intended schedule change:
//!
//! ```text
//! UPDATE_GOLDEN=1 cargo test --test golden_grids
//! ```
//! then read the diff line by line against the primary source before committing.

use std::fmt::Write as _;
use std::path::PathBuf;

use exchange_hours::{
    Exchange, MarketHours, MarketHoursKey, SessionRule, hours_for_exchange,
    hours_for_market_hours_key,
};

fn golden_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden/normal_week_grids.txt")
}

fn day_mask(days: [bool; 7]) -> String {
    const NAMES: [&str; 7] = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"];
    let mut out = String::new();
    for (index, name) in NAMES.iter().enumerate() {
        if days[index] {
            out.push_str(name);
        } else {
            out.push_str("--");
        }
    }
    out
}

fn clock(ssm: u32) -> String {
    format!("{:02}:{:02}:{:02}", ssm / 3600, (ssm % 3600) / 60, ssm % 60)
}

fn render_rules(out: &mut String, identity: &str, kind: &str, rules: &[SessionRule]) {
    if rules.is_empty() {
        let _ = writeln!(out, "{identity} | {kind} | (none)");
        return;
    }
    for rule in rules {
        let wrap = if rule.close_ssm <= rule.open_ssm {
            " +1d"
        } else {
            ""
        };
        let _ = writeln!(
            out,
            "{identity} | {kind} | {} | {}-{}{wrap}",
            day_mask(rule.days),
            clock(rule.open_ssm),
            clock(rule.close_ssm),
        );
    }
}

fn render(identity: &str, hours: &MarketHours) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "{identity} | tz {} | week_open_seconds {}",
        hours.tz,
        hours.normal_week_open_seconds()
    );
    render_rules(&mut out, identity, "regular ", &hours.regular);
    render_rules(&mut out, identity, "extended", &hours.extended);
    render_rules(&mut out, identity, "order-en", &hours.order_entry);
    out
}

fn render_all() -> String {
    let mut out = String::new();
    out.push_str("# Generated by tests/golden_grids.rs - do not hand-edit.\n");
    out.push_str("# Regenerate: UPDATE_GOLDEN=1 cargo test --test golden_grids\n");
    out.push_str(
        "# Columns: identity | phase | MoTuWeThFrSaSu mask | open-close (+1d = wraps)\n\n",
    );

    out.push_str("## Exchange (current profiles)\n");
    for exchange in Exchange::ALL {
        out.push_str(&render(
            exchange.as_str(),
            &hours_for_exchange(
                *exchange,
                chrono::DateTime::<chrono::Utc>::UNIX_EPOCH
                    + chrono::Duration::seconds(1_787_400_000),
            ),
        ));
    }

    out.push_str("\n## MarketHoursKey (current profiles)\n");
    for key in MarketHoursKey::ALL {
        out.push_str(&render(
            key.as_str(),
            &hours_for_market_hours_key(
                *key,
                chrono::DateTime::<chrono::Utc>::UNIX_EPOCH
                    + chrono::Duration::seconds(1_787_400_000),
            ),
        ));
    }
    out
}

#[test]
fn shipped_grids_match_the_golden_file() {
    let rendered = render_all();
    let path = golden_path();

    if std::env::var_os("UPDATE_GOLDEN").is_some() {
        if let Some(parent) = path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        std::fs::write(&path, &rendered).ok();
        return;
    }

    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert!(
        !committed.is_empty(),
        "golden file missing at {}; regenerate with UPDATE_GOLDEN=1 cargo test --test golden_grids",
        path.display()
    );

    if committed != rendered {
        let first_difference = committed
            .lines()
            .zip(rendered.lines())
            .enumerate()
            .find(|(_, (a, b))| a != b)
            .map_or_else(
                || "line counts differ".to_owned(),
                |(index, (committed_line, rendered_line))| {
                    format!(
                        "line {}:\n  committed: {committed_line}\n  shipped:   {rendered_line}",
                        index + 1
                    )
                },
            );
        panic!(
            "shipped normal-week grids differ from the golden file.\n{first_difference}\n\n\
             If this change is intended, verify it against the primary source, then run\n\
             UPDATE_GOLDEN=1 cargo test --test golden_grids and commit the diff."
        );
    }
}
